### ISSUE TITLE
Throwing an error if a field is null or undefined 

### ISSUE THREAD

**Issue by hbakhtiyor** [pleerock/class-validator#8]
the example using validation decorators, 

e.g.

```ts
    @Field()
    @MinLength(125)
    @MaxLength(2000)
    mission: string;
```

```
TypeError: This library (validator.js) validates strings only
    at assertString (/var/www/demo-app/node_modules/validator/lib/util/assertString.js:9:11)
    at Object.isLength (/var/www/demo-app/node_modules/validator/lib/isLength.js:19:30)
    at Validator.isLength (/var/www/demo-app/node_modules/validator.ts/Validator.js:345:30)
    at Validator.performValidation (/var/www/demo-app/node_modules/validator.ts/Validator.js:586:29)
    at /var/www/demo-app/node_modules/validator.ts/Validator.js:47:37
    at Array.map (native)
    at /var/www/demo-app/node_modules/validator.ts/Validator.js:40:45
    at Array.map (native)
    at Validator.validate (/var/www/demo-app/node_modules/validator.ts/Validator.js:35:26)
    at /var/www/demo-app/node_modules/validator.ts/Validator.js:90:32
```

**Comment by pleerock** [comment]
fixed in 0.2.2

**Comment by hbakhtiyor** [comment]
the error still there
if an object contains few fields and another is missing, .e.g `{ tweet: "bla" }`

**Comment by pleerock** [comment]
there should not be such error from 0.4.0
